README.md, src/get_maintainer_wrapper.sh, src/miscellaneous.sh, src/utils.sh, tests/get_maintainer_wrapper_test.sh, tests/samples/print_file_author_test_dir/code1.c, tests/samples/print_file_author_test_dir/code2.c
This PR adds an option 'kw maintainers [-a|--authors]' which, when used, prints the module's authors of the given file. If the given file is a directory, it prints the authors for each file in the given dir.
=> Option --authors to 'kw maintainers'

README.md
A very simple PR to add this info about run_tests to README: it must only be run from the repository's root.
Closes  #46
=> Add run_tests execution dir restriction to README

.gitignore, run_tests.sh, src/get_maintainer_wrapper.sh, tests/get_maintainer_wrapper_test.sh, tests/samples/MAINTAINERS, tests/utils
This PR makes  'kw maintainers' work  from any directory. It fixes #28 
It does that looking for he kernel tree root, cd-ing to it before running get_maintainers and cd-ing back after.
=> Make 'kw maintainers' work from any directory

src/checkpatch_wrapper.sh, tests/checkpatch_wrapper_test.sh
Currently, if we use 'kw c' in a source file without any warning, it
displays something like this:
$ kw c drivers/gpu/drm/vkms/
Running checkpatch.pl on: drivers/gpu/drm/vkms/
=========================================================
PATH:70: ANY OUTPUT
total: 0 errors, 0 warnings, 1 checks, 144 lines checked
=========================================================
=========================================================
=========================================================
=========================================================
This patch, fix this problem by removing the extra "=*". Additionally,
this commit updates the test to better fit this new output and add a new
check for the case that does not have any issue in the code.
Signed-off-by: Rodrigo Siqueira …
=> Fix the extra '=*' in the codestyle command

README.md, kw, setup.sh, src/commons.sh, src/config_manager.sh, src/help.sh, src/kwio.sh, tests/configm_test.sh
This commit adds the configure manager (configm) option, which is
responsible for administering the '.config' files for users. This commit
introduces the basic structure for configm followed by the save and list
operation. Additionally, the README and the unit tests were updated to
describe this feature better.
=> configm: Add '.config' manager with save and list

src/bash_autocomplete.sh
Remove the following deprecated commands completions for bash: mail, boot, bo.
There's a test case (testExplore) that fails. However, that case fails even in the unstable branch on my machine. I'm using shunit 2.7.1 and bash 5.0.2.
=> Remove depecrated commands from bash autocomplete

README.md, kw, src/help.sh, src/vm.sh, tests/samples/dmesg, tests/ssh_test.sh
This commit adds the capability of executing commands or scripts via kw
s. We have two options:
1. Commands: the command to be executed inside the VM
2. Scripts: A script in the host machine to be executed in the VM.
=> src: vm: Add support to execute commands/scripts via ssh

README.md, setup.sh, src/kw.fish, tests/fish_completion_test.sh
This is a fresher version of https://github.com/rodrigosiqueira/kworkflow/pull/88.
With this PR, `setup.sh` -i will configure `fish` for using `kw`, putting the completion file in the correct place, and adding `kw` to `fish` `PATH` variable.
=> Add fish support

documentation/content/installanduninstall.rst
rsync is needed by setup.sh to install kw and fish is needed as a
development dependency for tests.
Closes #82
=> documentation: install: add rsync and fish as dependencies

etc/kworkflow.config, src/kwio.sh
We noticed that the command `notify-send` behaves differently in Debian
and ArchLinux. After inspecting the code, we saw that kw does not put
the command in background; for this reason, this commit make kw put a
notification execution in background.
=> src: kwio: Make notification run in background

README.md, documentation/content/howtocontribute.rst
We now have https://github.com/kworkflow/kworkflow/, let's use it in links instead of the old repo location. Also use FLUSP's hosting of the docs when linking to online docs.
=> Some small fixes to use the newly created organization in links

documentation/content/installanduninstall.rst, documentation/man/kw.rst, kw, src/bash_autocomplete.sh, src/help.sh, src/kw.fish, src/vm.sh, tests/fish_completion_test.sh
When we started to develop kw, we want to make the Kernel developer's
life as easy as possible. For this reason, we added a feature named
prepare that uses Ansible scripts to put a VM in a well-known state.
However, after a long time of experiments, we realize that it is hard to
maintain such feature generic, and it also adds much complexity.
Additionally, some people start to package kw for Arch and Debian, which
means that Ansible represents another dependency for kworkflow. For all
of these reasons, we decided to drop this feature because it adds much
complexity, and the final result does not bring many benefits for
end-users.
=> Drop prepare feature

documentation/man/kw.rst, kw, setup.sh, src/VERSION, src/bash_autocomplete.sh, src/help.sh
Currently, we don't have a mechanism to show kw version, this commit
introduces this option. Notice that `setup.sh` update the version during
the installation, however, we keep a new file named VERSION with the
generic version info for distro packages.
Closes #163
=> src: version: Add version output

documentation/content/codingstyle.rst, tests/configm_test.sh, tests/get_maintainer_wrapper_test.sh, tests/help_test.sh, tests/kw_config_loader_test.sh, tests/kw_dash.sh, tests/kw_test.sh, tests/kwio_test.sh, tests/kwlib_test.sh, tests/ssh_test.sh
Our tests name are not well-formatted for historical reasons; for this
reason, this commits alleviate this issue by applying a similar pattern
for all test names. Additionally, we also update the documentation to
describe this new pattern better.
Closes #152
=> tests: standardization of test names

src/plugins/kernel_install/arch.sh
The mkinitcpio is not used for vm deployment, but used for other
targets.
Fixes: 5d75cfa3 ("Add support for VM deploy")
Signed-off-by: Melissa Wen <melissa.srw@gmail.com>
=> plugins: arch: fix the misuse of mkinitcpio on vm deployment

run_tests.sh
When `./run_tests.sh list` is run, the following warning appears:
`./run_tests.sh: line 179: local: can only be used in a function`
This PR fixes the warning by declaring the 'index' variable globally.
=> run_tests: remove warning when running ./run_tests.sh list

src/init.sh
Currently, when we show the available architecture, we list them from
arch/ folder. However, this can cause test failures because every system
can sort this information in its own way; i.e., tests are not portable
right now. This commit enforces dictionary order when we list
architecture to avoid failures in different distributions.
=> src: init: Enforce dictionary order when display architecture

documentation/dependencies/arch.dependencies, documentation/dependencies/debian.dependencies, etc/kworkflow_template.config, src/bash_autocomplete.sh, src/deploy.sh, src/kw_config_loader.sh, src/kwlib.sh, src/plugins/kernel_install/arch.sh, src/plugins/kernel_install/debian.sh, src/plugins/kernel_install/grub.sh, src/plugins/kernel_install/remote_deploy.sh, src/plugins/kernel_install/utils.sh, src/remote.sh, tests/configm_test.sh, tests/deploy_test.sh, tests/kw_config_loader_test.sh, tests/kwlib_test.sh, tests/plugins/kernel_install/utils_test.sh, tests/remote_test.sh, tests/samples/kworkflow.config, tests/utils.sh
I have been working to improve the overall quality of the deploy code; as a result, this PR is part of this effort. Here, you will see some simple code refactor that will make adding support for other distros and systems easier.
=> Deploy refinement

src/build.sh, tests/build_test.sh
We tried to add olddefconfig as a step to be executed before building
the kernel to avoid the interactive menu. However, the first
implementation did not work well in a cross-compiled environment, and we
had to revert it. This commit brings it back and reworks the build tests
to make them more readable.
Closes #393
Signed-off-by: Rodrigo Siqueira <siqueirajordao@riseup.net>
=> src: build: Add olddefconfig to build

src/report.sh, tests/report_test.sh, tests/samples/pomodoro_data/2021/04/05
Since the data fields in the pomodoro files are separated by commas,
when `cut -d ',' -f4` was used to retrieve the descriptions, if they
contained one or more commas, any part of the description that was after
the first comma would be left out. Now the description is retrieved as
the complement of the rest of the data.
Closes #495
Signed-off-by: Rubens Gomes Neto <rubens.gomes.neto@alumni.usp.br>
=> src: report: fix descriptions with commas

documentation/tutorials/rpi-deploy-kernel.rst, etc/init_templates/rpi4-raspbian-32-cross-x86-arm/deploy.config, etc/init_templates/rpi4-raspbian-64-cross-x86-arm/deploy.config
The RPI needs to keep the modules after they are installed, but the default kworkflow template states ``strip_modules_debug_option=yes``. So, explicitly tell the user that it is necessary to set ``strip_modules_debug_option=no`` on the config files.
Signed-off-by: Maíra Canal <mairacanal@riseup.net>
=> documentation: tutorial: Add note on the deploy.config for the RPI

kw, src/help.sh
While testing some of the kw package features, I noticed some features behave differently than expected due to wrong paths. This commit updates kw to use the correct paths if it is installed system-wide.
=> src: help: Add system-wide paths

src/deploy.sh, src/plugins/kernel_install/arch.sh, src/plugins/kernel_install/debian.sh, src/plugins/kernel_install/fedora.sh, src/plugins/kernel_install/grub.sh, src/plugins/kernel_install/remote_deploy.sh, src/plugins/kernel_install/rpi_bootloader.sh, src/plugins/kernel_install/utils.sh, tests/unit/deploy_test.sh, tests/unit/plugins/kernel_install/arch_test.sh, tests/unit/plugins/kernel_install/bootloader_utils_test.sh, tests/unit/plugins/kernel_install/debian_test.sh, tests/unit/plugins/kernel_install/fedora_test.sh, tests/unit/plugins/kernel_install/grub_test.sh, tests/unit/plugins/kernel_install/rpi_test.sh, tests/unit/plugins/kernel_install/utils_test.sh
I'm preparing a deploy refactor, but before that, I need to apply some basic kw code style to avoid noise in the PR review. This PR basically applies these two code-style rules to deploy related files:
- https://kworkflow.org/content/codingstyle.html#avoid-short-options
- https://kworkflow.org/content/codingstyle.html#string-concatenation
=> Apply part of the kw code style to the deploy files

documentation/tutorials/setup.rst
The link to the QEMU tutorial available on the flusp webpage changed. This commit fixes the link issue.
Closes: #1199
=> documentation: tutorial: Fix flusp link

src/kw_env.sh
Sometimes, switching to a different environment may fail, and kw does not provide helpful information about the reason. This commit enhances the output in the event of failures.
=> src: kw_env: Improve log message when switch env fails
